name: Swift

on:
  push:
    branches:
      - master/7.0
  pull_request:
    branches:
      - master/7.0

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        dbimage:
          - mongo
        runner:
          - swift:5.6-focal
          - swiftlang/swift:nightly-main-focal
    container: ${{ matrix.runner }}
    runs-on: ubuntu-latest
    services:
      mongo-a:
        image: ${{ matrix.dbimage }}
      mongo-b:
        image: ${{ matrix.dbimage }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test
        env:
          MONGO_HOSTNAME_A: mongo-a
          MONGO_HOSTNAME_B: mongo-b
